export const PERMISSIONS = {
    //   Admin related permissions
    //   Dashboard
    ADMIN_DASHBOARD_VIEW: "ADMIN_DASHBOARD_VIEW",
    // Users
    ADMIN_USERS_MANAGE: "ADMIN_USERS_MANAGE",
    ADMIN_USERS_CREATE: "ADMIN_USERS_CREATE",
    ADMIN_USERS_VIEW: "ADMIN_USERS_VIEW",
    ADMIN_USERS_UPDATE: "ADMIN_USERS_UPDATE",
    ADMIN_USERS_DELETE: "ADMIN_USERS_DELETE",
    ADMIN_USERS_EXPORT: "ADMIN_USERS_EXPORT",
    // Permissions
    ADMIN_PERMISSIONS_MANAGE: "ADMIN_PERMISSIONS_MANAGE",
    ADMIN_PERMISSIONS_CREATE: "ADMIN_PERMISSIONS_CREATE",
    ADMIN_PERMISSIONS_VIEW: "ADMIN_PERMISSIONS_VIEW",
    ADMIN_PERMISSIONS_UPDATE: "ADMIN_PERMISSIONS_UPDATE",
    ADMIN_PERMISSIONS_DELETE: "ADMIN_PERMISSIONS_DELETE",
    ADMIN_PERMISSIONS_EXPORT: "ADMIN_PERMISSIONS_EXPORT",
    // Roles
    ADMIN_ROLES_MANAGE: "ADMIN_ROLES_MANAGE",
    ADMIN_ROLES_CREATE: "ADMIN_ROLES_CREATE",
    ADMIN_ROLES_VIEW: "ADMIN_ROLES_VIEW",
    ADMIN_ROLES_UPDATE: "ADMIN_ROLES_UPDATE",
    ADMIN_ROLES_DELETE: "ADMIN_ROLES_DELETE",
    ADMIN_ROLES_EXPORT: "ADMIN_ROLES_EXPORT",
    //   Staff
    ADMIN_STAFF_MANAGE: "ADMIN_STAFF_MANAGE",
    ADMIN_STAFF_CREATE: "ADMIN_STAFF_CREATE",
    ADMIN_STAFF_VIEW: "ADMIN_STAFF_VIEW",
    ADMIN_STAFF_UPDATE: "ADMIN_STAFF_UPDATE",
    ADMIN_STAFF_DELETE: "ADMIN_STAFF_DELETE",
    ADMIN_STAFF_EXPORT: "ADMIN_STAFF_EXPORT",
    //   Navigation
    ADMIN_NAVIGATION_MANAGE: "ADMIN_NAVIGATION_MANAGE",
    ADMIN_NAVIGATION_CREATE: "ADMIN_NAVIGATION_CREATE",
    ADMIN_NAVIGATION_VIEW: "ADMIN_NAVIGATION_VIEW",
    ADMIN_NAVIGATION_UPDATE: "ADMIN_NAVIGATION_UPDATE",
    ADMIN_NAVIGATION_DELETE: "ADMIN_NAVIGATION_DELETE",
    ADMIN_NAVIGATION_EXPORT: "ADMIN_NAVIGATION_EXPORT",
    // Audit Logs
    ADMIN_AUDIT_LOGS_VIEW: "ADMIN_AUDIT_LOGS_VIEW",

    //   Organization related permissions
    ORG_DASHBOARD_VIEW: "ORG_DASHBOARD_VIEW",
    ORG_USERS_MANAGE: "ORG_USERS_MANAGE",
    ORG_USERS_VIEW: "ORG_USERS_VIEW",
    ORG_USERS_UPDATE: "ORG_USERS_UPDATE",
    ORG_USERS_DELETE: "ORG_USERS_DELETE",
};
