import {
  //   cibCcAmex,
  //   cibCcApplePay,
  //   cibCcMastercard,
  //   cibCcPaypal,
  //   cibCcStripe,
  //   cibCcVisa,
  //   cibFacebook,
  //   cibGoogle,
  //   cibLinkedin,
  //   cibSkype,
  //   cibTwitter,
  //   cifBr,
  //   cifEs,
  //   cifFr,
  //   cifIn,
  //   cifPl,
  //   cifUs,
  //   cilAccountLogout,
  //   cilAlignCenter,
  //   cilAlignLeft,
  //   cilAlignRight,
  //   cilApplicationsSettings,
  //   cilArrowBottom,
  //   cilArrowRight,
  //   cilArrowTop,
  // cilBarChart,
  //   cilBasket,
  //   cilBell,
  //   cilBold,
  //   cilBookmark,
  cilBolt,
  //   cilCalculator,
  //   cilCalendar,
  //   cilChart,
  //   cilChartPie,
  //   cilCheck,
  //   cilChevronLeft,
  //   cilChevronRight,
  //   cilCloudDownload,
  //   cilCode,
  //   cilColumns,
  //   cilCommentSquare,
  //   cilContact,
  //   cilContrast,
  //   cilCreditCard,
  //   cilCursor,
  //   cilDescription,
  //   cilDollar,
  //   cilDrop,
  //   cilEnvelopeClosed,
  //   cilEnvelopeOpen,
  //   cilEqualizer,
  //   cilExternalLink,
  //   cilFile,
  cilGraph,
  //   cilGrid,
  cilGroup,
  //   cilHome,
  cilHttps,
  //   cilInbox,
  //   cilIndentDecrease,
  //   cilIndentIncrease,
  //   cilItalic,
  //   cilJustifyCenter,
  //   cilLanguage,
  //   cilLayers,
  //   cilList,
  //   cilListNumbered,
  cilListRich,
  //   cilLocationPin,
  cilLockLocked,
  //   cilLoop,
  //   cilLoopCircular,
  //   cilMagnifyingGlass,
  //   cilMap,
  //   cilMediaPlay,
  //   cilMediaRecord,
  cilMenu,
  //   cilMoon,
  //   cilNotes,
  //   cilOptions,
  //   cilPaperclip,
  //   cilPaperPlane,
  //   cilPen,
  //   cilPencil,
  cilPeople,
  //   cilPlus,
  //   cilPrint,
  //   cilPuzzle,
  //   cilReportSlash,
  //   cilSave,
  //   cilSettings,
  //   cilShare,
  //   cilShareAll,
  //   cilShareBoxed,
  //   cilSpeech,
  //   cilSpeedometer,
  //   cilSpreadsheet,
  //   cilStar,
  //   cilSun,
  //   cilTags,
  //   cilTask,
  //   cilTrash,
  //   cilUnderline,
  cilUser,
  //   cilUserFemale,
  //   cilUserFollow,
  //   cilUserUnfollow
} from '@coreui/icons';

export const iconSubset = {
  //   cibCcAmex,
  //   cibCcApplePay,
  //   cibCcMastercard,
  //   cibCcPaypal,
  //   cibCcStripe,
  //   cibCcVisa,
  //   cibFacebook,
  //   cibGoogle,
  //   cibLinkedin,
  //   cibSkype,
  //   cibTwitter,
  //   cifBr,
  //   cifEs,
  //   cifFr,
  //   cifIn,
  //   cifPl,
  //   cifUs,
  //   cilAccountLogout,
  //   cilAlignCenter,
  //   cilAlignLeft,
  //   cilAlignRight,
  //   cilApplicationsSettings,
  //   cilArrowBottom,
  //   cilArrowRight,
  //   cilArrowTop,
  // cilBarChart,
  //   cilBasket,
  //   cilBell,
  //   cilBold,
  //   cilBookmark,
  cilBolt,
  //   cilCalculator,
  //   cilCalendar,
  //   cilChart,
  //   cilChartPie,
  //   cilCheck,
  //   cilChevronLeft,
  //   cilChevronRight,
  //   cilCloudDownload,
  //   cilCode,
  //   cilColumns,
  //   cilCommentSquare,
  //   cilContact,
  //   cilContrast,
  //   cilCreditCard,
  //   cilCursor,
  //   cilDescription,
  //   cilDollar,
  //   cilDrop,
  //   cilEnvelopeClosed,
  //   cilEnvelopeOpen,
  //   cilEqualizer,
  //   cilExternalLink,
  //   cilFile,
  cilGraph,
  //   cilGrid,
  cilGroup,
  //   cilHome,
  cilHttps,
  //   cilInbox,
  //   cilIndentDecrease,
  //   cilIndentIncrease,
  //   cilItalic,
  //   cilJustifyCenter,
  //   cilLanguage,
  //   cilLayers,
  //   cilList,
  //   cilListNumbered,
  cilListRich,
  //   cilLocationPin,
  cilLockLocked,
  //   cilLoop,
  //   cilLoopCircular,
  //   cilMagnifyingGlass,
  //   cilMap,
  //   cilMediaPlay,
  //   cilMediaRecord,
  cilMenu,
  //   cilMoon,
  //   cilNotes,
  //   cilOptions,
  //   cilPaperclip,
  //   cilPaperPlane,
  //   cilPen,
  //   cilPencil,
  cilPeople,
  //   cilPlus,
  //   cilPrint,
  //   cilPuzzle,
  //   cilReportSlash,
  //   cilSave,
  //   cilSettings,
  //   cilShare,
  //   cilShareAll,
  //   cilShareBoxed,
  //   cilSpeech,
  //   cilSpeedometer,
  //   cilSpreadsheet,
  //   cilStar,
  //   cilSun,
  //   cilTags,
  //   cilTask,
  //   cilTrash,
  //   cilUnderline,
  cilUser,
  //   cilUserFemale,
  //   cilUserFollow,
  //   cilUserUnfollow,
};
